package com.example.servletsample.samples.test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import com.example.servletsample.common.Database;

/**
 * 【サンプル】本番用の {@link OrderRepository}。組み込みデータベース (H2) を使う。
 *
 * <p>SQL を書くのはこのクラスの仕事、金額のルールを決めるのは {@link OrderPricing} の仕事、
 * 手順をまとめるのは {@link OrderService} の仕事、と分けてあります。</p>
 *
 * <p>このクラス自体は DB が無いとテストできません。それで構いません。
 * <b>DB が要る部分をここに閉じ込めた</b>からこそ、
 * 業務ルールのテスト (OrderPricingTest / OrderServiceTest) は DB 無しで書けています。
 * このクラスを確かめたいときは、H2 を実際に動かすテスト
 * (このサイトの {@code ProductDaoTest} や {@code TransferDaoTest} と同じやり方) を書きます。</p>
 */
public class JdbcOrderRepository implements OrderRepository {

    private static final String CREATE_ITEMS = """
            CREATE TABLE IF NOT EXISTS order_items (
                code       VARCHAR(16) PRIMARY KEY,
                name       VARCHAR(60) NOT NULL,
                unit_price INT         NOT NULL,
                stock      INT         NOT NULL,
                sort_order INT         NOT NULL
            )
            """;

    private static final String CREATE_ORDERS = """
            CREATE TABLE IF NOT EXISTS order_entries (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_number    VARCHAR(24)  NOT NULL,
                customer_name   VARCHAR(60)  NOT NULL,
                item_code       VARCHAR(16)  NOT NULL,
                item_name       VARCHAR(60)  NOT NULL,
                quantity        INT          NOT NULL,
                member_rank     VARCHAR(16)  NOT NULL,
                subtotal        INT          NOT NULL,
                bulk_discount   INT          NOT NULL,
                member_discount INT          NOT NULL,
                shipping_fee    INT          NOT NULL,
                tax             INT          NOT NULL,
                accepted_at     TIMESTAMP    NOT NULL
            )
            """;

    private static boolean tableReady;

    public JdbcOrderRepository() {
        prepareTable();
    }

    /** テーブルを作り、空なら商品マスタを入れる。 */
    public static synchronized void prepareTable() {
        if (tableReady) {
            return;
        }
        try (Connection connection = Database.getConnection();
             Statement statement = connection.createStatement()) {

            statement.execute(CREATE_ITEMS);
            statement.execute(CREATE_ORDERS);
            insertItemsIfEmpty(connection);
            tableReady = true;
        } catch (SQLException e) {
            throw new IllegalStateException("order_items テーブルを準備できませんでした", e);
        }
    }

    @Override
    public List<Item> findItems() {
        List<Item> items = new ArrayList<>();
        String sql = "SELECT code, name, unit_price, stock FROM order_items ORDER BY sort_order";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet rs = statement.executeQuery()) {

            while (rs.next()) {
                items.add(toItem(rs));
            }
        } catch (SQLException e) {
            throw new IllegalStateException("商品を取得できませんでした", e);
        }
        return items;
    }

    @Override
    public Optional<Item> findItem(String code) {
        if (code == null || code.isEmpty()) {
            return Optional.empty();
        }
        String sql = "SELECT code, name, unit_price, stock FROM order_items WHERE code = ?";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, code);
            try (ResultSet rs = statement.executeQuery()) {
                return rs.next() ? Optional.of(toItem(rs)) : Optional.empty();
            }
        } catch (SQLException e) {
            throw new IllegalStateException("商品を取得できませんでした: " + code, e);
        }
    }

    @Override
    public void decreaseStock(String itemCode, int quantity) {
        String sql = "UPDATE order_items SET stock = stock - ? WHERE code = ?";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setInt(1, quantity);
            statement.setString(2, itemCode);
            statement.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException("在庫を更新できませんでした: " + itemCode, e);
        }
    }

    @Override
    public int countOrders() {
        String sql = "SELECT COUNT(*) FROM order_entries";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet rs = statement.executeQuery()) {

            return rs.next() ? rs.getInt(1) : 0;
        } catch (SQLException e) {
            throw new IllegalStateException("注文件数を取得できませんでした", e);
        }
    }

    @Override
    public void save(OrderEntry order) {
        String sql = """
                INSERT INTO order_entries
                    (order_number, customer_name, item_code, item_name, quantity, member_rank,
                     subtotal, bulk_discount, member_discount, shipping_fee, tax, accepted_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """;
        OrderAmount amount = order.getAmount();
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, order.getOrderNumber());
            statement.setString(2, order.getCustomerName());
            statement.setString(3, order.getItemCode());
            statement.setString(4, order.getItemName());
            statement.setInt(5, order.getQuantity());
            statement.setString(6, order.getMemberRank().name());
            statement.setInt(7, amount.getSubtotal());
            statement.setInt(8, amount.getBulkDiscount());
            statement.setInt(9, amount.getMemberDiscount());
            statement.setInt(10, amount.getShippingFee());
            statement.setInt(11, amount.getTax());
            statement.setTimestamp(12, java.sql.Timestamp.valueOf(order.getAcceptedAt()));
            statement.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException("注文を保存できませんでした", e);
        }
    }

    @Override
    public List<OrderEntry> findRecentOrders(int limit) {
        List<OrderEntry> orders = new ArrayList<>();
        String sql = """
                SELECT order_number, customer_name, item_code, item_name, quantity, member_rank,
                       subtotal, bulk_discount, member_discount, shipping_fee, tax, accepted_at
                  FROM order_entries
                 ORDER BY id DESC
                 LIMIT ?
                """;
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setInt(1, limit);
            try (ResultSet rs = statement.executeQuery()) {
                while (rs.next()) {
                    orders.add(new OrderEntry(
                            rs.getString("order_number"),
                            rs.getString("customer_name"),
                            rs.getString("item_code"),
                            rs.getString("item_name"),
                            rs.getInt("quantity"),
                            MemberRank.of(rs.getString("member_rank")),
                            new OrderAmount(rs.getInt("subtotal"), rs.getInt("bulk_discount"),
                                    rs.getInt("member_discount"), rs.getInt("shipping_fee"), rs.getInt("tax")),
                            rs.getTimestamp("accepted_at").toLocalDateTime()));
                }
            }
        } catch (SQLException e) {
            throw new IllegalStateException("注文を取得できませんでした", e);
        }
        return orders;
    }

    @Override
    public void reset() {
        try (Connection connection = Database.getConnection();
             Statement statement = connection.createStatement()) {

            statement.executeUpdate("DELETE FROM order_entries");
            statement.executeUpdate("DELETE FROM order_items");
            insertItemsIfEmpty(connection);
        } catch (SQLException e) {
            throw new IllegalStateException("注文サンプルを初期化できませんでした", e);
        }
    }

    private static Item toItem(ResultSet rs) throws SQLException {
        return new Item(rs.getString("code"), rs.getString("name"),
                rs.getInt("unit_price"), rs.getInt("stock"));
    }

    private static void insertItemsIfEmpty(Connection connection) throws SQLException {
        try (PreparedStatement count = connection.prepareStatement("SELECT COUNT(*) FROM order_items");
             ResultSet rs = count.executeQuery()) {
            if (rs.next() && rs.getInt(1) > 0) {
                return;
            }
        }
        String sql = "INSERT INTO order_items (code, name, unit_price, stock, sort_order) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            int order = 0;
            for (Item item : OrderSampleData.initialItems()) {
                statement.setString(1, item.getCode());
                statement.setString(2, item.getName());
                statement.setInt(3, item.getUnitPrice());
                statement.setInt(4, item.getStock());
                statement.setInt(5, ++order);
                statement.addBatch();
            }
            statement.executeBatch();
        }
    }
}
