package com.example.servletsample.samples.file;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UncheckedIOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.example.servletsample.common.Database;

/**
 * データベースに保存した PDF の取得 (DAO)。
 *
 * <p>PDF の中身は {@code BLOB} 列にそのまま入れています。
 * 見積書・請求書のような「システムが作って、あとから利用者が見返す帳票」は
 * この形で持つことがよくあります。</p>
 *
 * <p>表示のときに気をつけるのは 1 つだけで、<b>中身をいったん {@code byte[]} に読み込まない</b>ことです。
 * {@link #copyContentTo} のように、DB から読みながらそのままレスポンスへ流します。</p>
 */
public class PdfDocumentDao {

    /** テーブル定義。 */
    private static final String CREATE_TABLE = """
            CREATE TABLE IF NOT EXISTS pdf_documents (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title       VARCHAR(100) NOT NULL,
                file_name   VARCHAR(255) NOT NULL,
                file_size   BIGINT       NOT NULL,
                content     BLOB         NOT NULL,
                created_at  TIMESTAMP    NOT NULL
            )
            """;

    /** 一覧・1 件取得では中身 (content) を読まない。 */
    private static final String SELECT_COLUMNS =
            "SELECT id, title, file_name, file_size, created_at FROM pdf_documents";

    /**
     * 起動時に入れておく PDF。{ 同梱ファイル, 画面に出す名前, 保存するときのファイル名 }
     *
     * <p>サンプルなので、アプリに同梱した PDF ({@code src/main/resources/pdf-seed}) を
     * 起動時に DB へ入れています。実務では、帳票を作った処理や
     * アップロード画面 (「ファイルのアップロード」のサンプル) が入れることになります。</p>
     */
    private static final String[][] SEEDS = {
        {"/pdf-seed/estimate.pdf", "御見積書（Q-2026-0012）", "見積書_Q-2026-0012.pdf"},
        {"/pdf-seed/invoice.pdf", "請求書（INV-2026-0345）", "請求書_INV-2026-0345.pdf"},
        {"/pdf-seed/meeting.pdf", "定例会議資料（5 ページ）", "定例会議資料_2026年9月.pdf"},
    };

    private static boolean tableReady;

    public PdfDocumentDao() {
        prepareTable();
    }

    /**
     * テーブルを作り、空ならサンプルの PDF を入れる。
     *
     * <p>実務ではマイグレーションツール (Flyway など) の担当ですが、
     * このサンプル集は「起動したらすぐ動く」ことを優先して起動時に作っています。</p>
     */
    public static synchronized void prepareTable() {
        if (tableReady) {
            return;
        }
        try (Connection connection = Database.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(CREATE_TABLE);
            try (ResultSet rs = statement.executeQuery("SELECT COUNT(*) FROM pdf_documents")) {
                if (rs.next() && rs.getLong(1) == 0) {
                    for (String[] seed : SEEDS) {
                        insertSeed(connection, seed[0], seed[1], seed[2]);
                    }
                }
            }
            tableReady = true;
        } catch (SQLException e) {
            throw new IllegalStateException("pdf_documents テーブルを準備できませんでした", e);
        }
    }

    /** 同梱の PDF を 1 件 DB に入れる。 */
    private static void insertSeed(Connection connection, String resource, String title, String fileName)
            throws SQLException {
        byte[] content;
        try (InputStream in = PdfDocumentDao.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("サンプルの PDF が見つかりません: " + resource);
            }
            // 起動時に 1 回だけ読む小さなファイルなので、ここでは byte[] で受けている
            content = in.readAllBytes();
        } catch (IOException e) {
            throw new UncheckedIOException("サンプルの PDF を読み込めませんでした: " + resource, e);
        }

        String sql = """
                INSERT INTO pdf_documents (title, file_name, file_size, content, created_at)
                VALUES (?, ?, ?, ?, ?)
                """;
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, title);
            statement.setString(2, fileName);
            statement.setLong(3, content.length);
            statement.setBytes(4, content);
            statement.setObject(5, LocalDateTime.now());
            statement.executeUpdate();
        }
    }

    /** 一覧を取得する (中身は読み込まない)。 */
    public List<PdfDocument> findAll() {
        List<PdfDocument> documents = new ArrayList<>();
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(SELECT_COLUMNS + " ORDER BY id");
             ResultSet rs = statement.executeQuery()) {

            while (rs.next()) {
                documents.add(toDocument(rs));
            }
            return documents;
        } catch (SQLException e) {
            throw new IllegalStateException("PDF の一覧を取得できませんでした", e);
        }
    }

    /** ID で 1 件取得する (中身は読み込まない)。見つからなければ null。 */
    public PdfDocument findById(long id) {
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(SELECT_COLUMNS + " WHERE id = ?")) {

            statement.setLong(1, id);
            try (ResultSet rs = statement.executeQuery()) {
                return rs.next() ? toDocument(rs) : null;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("PDF の情報を取得できませんでした: id=" + id, e);
        }
    }

    /**
     * PDF の中身を出力先へ書き出す。
     *
     * <p>{@code byte[]} に読み込んでから返すのではなく、
     * DB から読みながらそのままレスポンスへ流します。
     * 大きな PDF を何人が同時に開いても、1 人あたり小さな読み書き用のバッファぶんで済みます。</p>
     *
     * @return 書き出せたら true、その ID が無ければ false
     */
    public boolean copyContentTo(long id, OutputStream out) throws IOException {
        String sql = "SELECT content FROM pdf_documents WHERE id = ?";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setLong(1, id);
            try (ResultSet rs = statement.executeQuery()) {
                if (!rs.next()) {
                    return false;
                }
                try (InputStream in = rs.getBinaryStream("content")) {
                    in.transferTo(out);
                }
                return true;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("PDF を読み出せませんでした: id=" + id, e);
        }
    }

    private static PdfDocument toDocument(ResultSet rs) throws SQLException {
        return new PdfDocument(
                rs.getLong("id"),
                rs.getString("title"),
                rs.getString("file_name"),
                rs.getLong("file_size"),
                rs.getObject("created_at", LocalDateTime.class));
    }
}
