package com.example.servletsample.samples.file;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.example.servletsample.common.Database;

/**
 * アップロードされたファイルの保存・取得・削除 (DAO)。
 *
 * <p>ファイルの中身は {@code BLOB} 列にそのまま入れています。
 * サーバのディスクに置く方式と比べると</p>
 * <ul>
 *   <li>バックアップやトランザクションが DB だけで完結する</li>
 *   <li>サーバを増やしてもファイルの置き場所を共有しなくてよい</li>
 * </ul>
 * <p>という利点があり、逆に大きなファイルには向きません
 * (数 MB を超えるものはストレージに置き、DB にはパスだけ持つ構成が一般的です)。</p>
 */
public class StoredFileDao {

    /** テーブル定義。 */
    private static final String CREATE_TABLE = """
            CREATE TABLE IF NOT EXISTS uploaded_files (
                id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                file_name    VARCHAR(255) NOT NULL,
                content_type VARCHAR(255) NOT NULL,
                file_size    BIGINT       NOT NULL,
                content      BLOB         NOT NULL,
                uploaded_at  TIMESTAMP    NOT NULL
            )
            """;

    /** 一覧では中身 (content) を読まない。 */
    private static final String SELECT_LIST = """
            SELECT id, file_name, content_type, file_size, uploaded_at
              FROM uploaded_files
             ORDER BY uploaded_at DESC, id DESC
            """;

    private static boolean tableReady;

    public StoredFileDao() {
        prepareTable();
    }

    /**
     * テーブルを作る (無ければ作る、あれば何もしない)。
     *
     * <p>実務ではマイグレーションツール (Flyway など) の担当ですが、
     * このサンプル集は「起動したらすぐ動く」ことを優先して起動時に作っています。</p>
     */
    public static synchronized void prepareTable() {
        if (tableReady) {
            return;
        }
        try (Connection connection = Database.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(CREATE_TABLE);
            tableReady = true;
        } catch (SQLException e) {
            throw new IllegalStateException("uploaded_files テーブルを作成できませんでした", e);
        }
    }

    /**
     * ファイルを保存する。
     *
     * @return 採番された ID
     */
    public long save(String fileName, String contentType, long size, InputStream content) {
        String sql = """
                INSERT INTO uploaded_files (file_name, content_type, file_size, content, uploaded_at)
                VALUES (?, ?, ?, ?, ?)
                """;
        try (Connection connection = Database.getConnection();
             PreparedStatement statement =
                     connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            statement.setString(1, fileName);
            statement.setString(2, contentType);
            statement.setLong(3, size);
            // 中身はストリームのまま渡す (いったん byte[] にしない方がメモリに優しい)
            statement.setBinaryStream(4, content, size);
            statement.setObject(5, LocalDateTime.now());
            statement.executeUpdate();

            try (ResultSet keys = statement.getGeneratedKeys()) {
                return keys.next() ? keys.getLong(1) : -1L;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("ファイルを保存できませんでした: " + fileName, e);
        }
    }

    /** 新しい順に一覧を取得する (中身は読み込まない)。 */
    public List<StoredFile> findAll() {
        List<StoredFile> files = new ArrayList<>();
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(SELECT_LIST);
             ResultSet rs = statement.executeQuery()) {

            while (rs.next()) {
                files.add(toStoredFile(rs));
            }
            return files;
        } catch (SQLException e) {
            throw new IllegalStateException("ファイル一覧を取得できませんでした", e);
        }
    }

    /** ID で 1 件取得する (中身は読み込まない)。見つからなければ null。 */
    public StoredFile findById(long id) {
        String sql = """
                SELECT id, file_name, content_type, file_size, uploaded_at
                  FROM uploaded_files
                 WHERE id = ?
                """;
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setLong(1, id);
            try (ResultSet rs = statement.executeQuery()) {
                return rs.next() ? toStoredFile(rs) : null;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("ファイル情報を取得できませんでした: id=" + id, e);
        }
    }

    /**
     * ファイルの中身を出力先へ書き出す (ダウンロード用)。
     *
     * <p>{@code byte[]} に読み込んでから返すのではなく、
     * DB から読みながらそのままレスポンスへ流します。
     * こうすると大きなファイルでもメモリの使用量が増えません。</p>
     *
     * @return 書き出せたら true、その ID が無ければ false
     */
    public boolean copyContentTo(long id, OutputStream out) throws IOException {
        String sql = "SELECT content FROM uploaded_files WHERE id = ?";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setLong(1, id);
            try (ResultSet rs = statement.executeQuery()) {
                if (!rs.next()) {
                    return false;
                }
                try (InputStream in = rs.getBinaryStream("content")) {
                    byte[] buffer = new byte[8192];
                    int read;
                    while ((read = in.read(buffer)) != -1) {
                        out.write(buffer, 0, read);
                    }
                }
                return true;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("ファイルを読み出せませんでした: id=" + id, e);
        }
    }

    /**
     * ファイルを削除する。
     *
     * @return 削除できたら true、その ID が無ければ false
     */
    public boolean delete(long id) {
        String sql = "DELETE FROM uploaded_files WHERE id = ?";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setLong(1, id);
            return statement.executeUpdate() > 0;
        } catch (SQLException e) {
            throw new IllegalStateException("ファイルを削除できませんでした: id=" + id, e);
        }
    }

    /** 保存されているファイルの合計バイト数。 */
    public long totalSize() {
        String sql = "SELECT COALESCE(SUM(file_size), 0) FROM uploaded_files";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet rs = statement.executeQuery()) {

            return rs.next() ? rs.getLong(1) : 0L;
        } catch (SQLException e) {
            throw new IllegalStateException("合計サイズを取得できませんでした", e);
        }
    }

    private static StoredFile toStoredFile(ResultSet rs) throws SQLException {
        return new StoredFile(
                rs.getLong("id"),
                rs.getString("file_name"),
                rs.getString("content_type"),
                rs.getLong("file_size"),
                rs.getObject("uploaded_at", LocalDateTime.class));
    }
}
