package com.example.servletsample.samples.advanced;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.servletsample.common.Database;

/**
 * 口座と振替のデータアクセス。トランザクションの扱い方を見せるためのクラスです。
 *
 * <h2>いちばん大事なこと : 同じ接続を使う</h2>
 * <p>トランザクションは<b>コネクション 1 本に対して</b>効きます。
 * 処理のたびに {@code Database.getConnection()} を呼んでいると、
 * それぞれが別のトランザクションになり、まとめて取り消せません。</p>
 *
 * <pre>{@code
 * // 【駄目な例】 DAO のメソッドがそれぞれ接続を開いている
 * accountDao.withdraw(fromId, amount);   // ← 接続 A。ここで確定してしまう
 * accountDao.deposit(toId, amount);      // ← 接続 B。ここで落ちても A は戻らない
 *
 * // 【良い例】 開いた接続を引き回す
 * try (Connection connection = Database.getConnection()) {
 *     connection.setAutoCommit(false);
 *     withdraw(connection, fromId, amount);
 *     deposit(connection, toId, amount);
 *     connection.commit();
 * }
 * }</pre>
 *
 * <p>そのため、個々の更新メソッドは<b>{@link Connection} を引数で受け取ります</b>。
 * 「どこからどこまでが 1 つのまとまりか」を決めるのは呼び出し側の仕事だからです。
 * 実務では、この「決める役」をサービス層に置きます。</p>
 *
 * <h2>自動コミット</h2>
 * <p>JDBC の既定は<b>自動コミット</b>で、1 文ごとに確定します。
 * まとめたいときは {@code setAutoCommit(false)} で切ります。</p>
 */
public class TransferDao {

    private static final String CREATE_ACCOUNTS = """
            CREATE TABLE IF NOT EXISTS accounts (
                id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code    VARCHAR(16) NOT NULL,
                name    VARCHAR(60) NOT NULL,
                balance INT         NOT NULL
            )
            """;

    private static final String CREATE_TRANSFERS = """
            CREATE TABLE IF NOT EXISTS transfers (
                id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                from_code VARCHAR(16) NOT NULL,
                to_code   VARCHAR(16) NOT NULL,
                amount    INT         NOT NULL
            )
            """;

    /** 初期残高。「元に戻す」で使います。 */
    private static final String[][] SEED = {
            {"A-001", "山田 太郎", "50000"},
            {"A-002", "鈴木 花子", "30000"},
            {"A-003", "佐藤 次郎", "10000"}
    };

    private static boolean tableReady;

    public TransferDao() {
        prepareTable();
    }

    /** テーブルを作り、空ならサンプルデータを入れる。 */
    public static synchronized void prepareTable() {
        if (tableReady) {
            return;
        }
        try (Connection connection = Database.getConnection();
             Statement statement = connection.createStatement()) {

            statement.execute(CREATE_ACCOUNTS);
            statement.execute(CREATE_TRANSFERS);
            if (isEmpty(connection)) {
                insertSeedData(connection);
            }
            tableReady = true;
        } catch (SQLException e) {
            throw new IllegalStateException("accounts テーブルを準備できませんでした", e);
        }
    }

    /** 口座の一覧。 */
    public List<Account> findAccounts() {
        List<Account> accounts = new ArrayList<>();
        String sql = "SELECT id, code, name, balance FROM accounts ORDER BY code";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet rs = statement.executeQuery()) {

            while (rs.next()) {
                accounts.add(new Account(rs.getLong("id"), rs.getString("code"),
                        rs.getString("name"), rs.getInt("balance")));
            }
        } catch (SQLException e) {
            throw new IllegalStateException("口座を取得できませんでした", e);
        }
        return accounts;
    }

    /** 残高の合計。振替のあとも変わらないはずの値です。 */
    public int totalBalance() {
        String sql = "SELECT SUM(balance) FROM accounts";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet rs = statement.executeQuery()) {

            return rs.next() ? rs.getInt(1) : 0;
        } catch (SQLException e) {
            throw new IllegalStateException("残高の合計を取得できませんでした", e);
        }
    }

    /** 振替の履歴 (新しい順に数件)。 */
    public List<String> recentTransfers(int limit) {
        List<String> history = new ArrayList<>();
        String sql = "SELECT from_code, to_code, amount FROM transfers ORDER BY id DESC LIMIT ?";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setInt(1, limit);
            try (ResultSet rs = statement.executeQuery()) {
                while (rs.next()) {
                    history.add(rs.getString("from_code") + " → " + rs.getString("to_code")
                            + "  " + rs.getInt("amount") + " 円");
                }
            }
        } catch (SQLException e) {
            throw new IllegalStateException("履歴を取得できませんでした", e);
        }
        return history;
    }

    /**
     * 振替を行う。
     *
     * <p>この 1 メソッドが「トランザクションの境界」です。
     * どこからどこまでを 1 つのまとまりにするかを、ここで決めています。</p>
     *
     * @param fromId         送金元の口座 ID
     * @param toId           送金先の口座 ID
     * @param amount         金額
     * @param useTransaction {@code false} にすると自動コミットのまま実行する (デモ用)
     * @param failMidway     {@code true} にすると出金のあとでわざと失敗する (デモ用)
     */
    public TransferOutcome transfer(long fromId, long toId, int amount,
                                    boolean useTransaction, boolean failMidway) {

        TransferOutcome outcome = new TransferOutcome(!useTransaction);

        try (Connection connection = Database.getConnection()) {

            if (useTransaction) {
                // ここから commit / rollback までが 1 つのまとまりになる
                connection.setAutoCommit(false);
                outcome.step("setAutoCommit(false) … 自動コミットを切った");
            } else {
                outcome.step("自動コミットのまま … 1 文ごとに確定してしまう");
            }

            try {
                // ---------------- ① 出金
                int withdrawn = withdraw(connection, fromId, amount);
                if (withdrawn == 0) {
                    // 更新できた行が 0 = 残高が足りなかった。
                    // 「残高を SELECT してから UPDATE」ではなく、
                    // UPDATE の条件に入れて件数で判断するのが安全です
                    // (SELECT と UPDATE の間に別の処理が割り込めないため)
                    throw new ApplicationException("E-4001", "残高が足りません。");
                }
                outcome.step("① 出金 … UPDATE accounts SET balance = balance - "
                        + amount + " WHERE id = " + fromId + " AND balance >= " + amount);

                // ---------------- ② わざと失敗する (デモ用)
                if (failMidway) {
                    throw new IllegalStateException(
                            "送金先の口座情報を取得できませんでした (このサンプルがわざと投げた例外です)");
                }

                // ---------------- ③ 入金
                deposit(connection, toId, amount);
                outcome.step("② 入金 … UPDATE accounts SET balance = balance + "
                        + amount + " WHERE id = " + toId);

                // ---------------- ④ 履歴
                insertHistory(connection, fromId, toId, amount);
                outcome.step("③ 履歴 … INSERT INTO transfers ...");

                if (useTransaction) {
                    connection.commit();
                    outcome.step("commit() … ここで初めて確定した");
                }
                outcome.committed("振替が完了しました。");

            } catch (RuntimeException e) {
                // ApplicationException (業務エラー) も RuntimeException なのでここへ来ます。
                // どちらであっても、やることは同じ「取り消して、何が起きたかを伝える」です
                rollbackIfNeeded(connection, useTransaction, outcome, e);
            } finally {
                // 接続をプールへ返す前に、必ず元に戻します。
                // 戻し忘れると、次にこの接続を借りた処理が
                // 「自動コミットが切れたまま」動き、commit されないまま終わります
                if (useTransaction) {
                    connection.setAutoCommit(true);
                }
            }

        } catch (SQLException e) {
            throw new IllegalStateException("振替に失敗しました", e);
        }
        return outcome;
    }

    /** 失敗したときの後始末。 */
    private void rollbackIfNeeded(Connection connection, boolean useTransaction,
                                  TransferOutcome outcome, RuntimeException e) throws SQLException {
        String errorType = e.getClass().getSimpleName();

        if (!useTransaction) {
            // 自動コミットなので、ここまでの更新は確定済み。取り消せない
            outcome.step("例外が発生 … しかし自動コミットなので、出金だけが確定したまま残る");
            outcome.failedWithoutRollback(e.getMessage(), errorType);
            return;
        }
        connection.rollback();
        outcome.step("rollback() … ①以降の更新をすべて取り消した");
        outcome.rolledBack(e.getMessage(), errorType);
    }

    /**
     * 出金する。
     *
     * <p>{@code AND balance >= ?} を条件に入れているのが要点です。
     * 「残高を SELECT して、足りていれば UPDATE」と書くと、
     * その 2 つの間に別のリクエストが割り込んで<b>残高がマイナスになりえます</b>。
     * 判定を UPDATE の条件に含めてしまえば、データベースが 1 つの操作として扱ってくれます。</p>
     *
     * @return 更新できた行数 (0 なら残高不足)
     */
    private int withdraw(Connection connection, long accountId, int amount) throws SQLException {
        String sql = "UPDATE accounts SET balance = balance - ? WHERE id = ? AND balance >= ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, amount);
            statement.setLong(2, accountId);
            statement.setInt(3, amount);
            return statement.executeUpdate();
        }
    }

    /** 入金する。 */
    private void deposit(Connection connection, long accountId, int amount) throws SQLException {
        String sql = "UPDATE accounts SET balance = balance + ? WHERE id = ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, amount);
            statement.setLong(2, accountId);
            statement.executeUpdate();
        }
    }

    /** 履歴を残す。 */
    private void insertHistory(Connection connection, long fromId, long toId, int amount)
            throws SQLException {
        String sql = """
                INSERT INTO transfers (from_code, to_code, amount)
                SELECT f.code, t.code, ? FROM accounts f, accounts t WHERE f.id = ? AND t.id = ?
                """;
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, amount);
            statement.setLong(2, fromId);
            statement.setLong(3, toId);
            statement.executeUpdate();
        }
    }

    /** 残高と履歴を初期状態に戻す (サンプルを何度も試せるように)。 */
    public void reset() {
        try (Connection connection = Database.getConnection()) {
            connection.setAutoCommit(false);
            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate("DELETE FROM transfers");
                statement.executeUpdate("DELETE FROM accounts");
                insertSeedData(connection);
                connection.commit();
            } catch (SQLException e) {
                connection.rollback();
                throw e;
            } finally {
                connection.setAutoCommit(true);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("初期化に失敗しました", e);
        }
    }

    private static boolean isEmpty(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT COUNT(*) FROM accounts")) {
            return rs.next() && rs.getInt(1) == 0;
        }
    }

    private static void insertSeedData(Connection connection) throws SQLException {
        String sql = "INSERT INTO accounts (code, name, balance) VALUES (?, ?, ?)";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            for (String[] row : SEED) {
                statement.setString(1, row[0]);
                statement.setString(2, row[1]);
                statement.setInt(3, Integer.parseInt(row[2]));
                statement.addBatch();
            }
            statement.executeBatch();
        }
    }
}
