package com.example.servletsample.samples.list;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import com.example.servletsample.common.Database;

/**
 * 取引先マスタのデータアクセス。
 *
 * <p>「マスタメンテナンス」と「更新の競合（楽観ロック）」の 2 つのサンプルで共有しています。</p>
 *
 * <h2>楽観ロック</h2>
 * <p>更新の条件に {@code version} を入れ、<b>更新できた行数で競合を判断します</b>。</p>
 *
 * <pre>{@code
 * UPDATE customers
 *    SET name = ?, version = version + 1, updated_at = ?
 *  WHERE id = ? AND version = ?
 *                  ~~~~~~~~~~~~~ 画面を開いたときの version
 *
 * executeUpdate() == 1 → 更新できた (誰も触っていなかった)
 * executeUpdate() == 0 → 誰かが先に更新していた (または行が消えていた)
 * }</pre>
 *
 * <p>ここで大事なのは<b>「先に SELECT して version を比べる」ことをしない</b>点です。
 * SELECT と UPDATE の間に割り込まれたら、結局すり抜けます。
 * <b>1 文の UPDATE の条件に入れる</b>ので、割り込む隙間がありません。</p>
 *
 * <h2>悲観ロックとの違い</h2>
 * <table border="1">
 *   <caption>どちらを使うか</caption>
 *   <tr><th></th><th>楽観ロック</th><th>悲観ロック</th></tr>
 *   <tr><td>やり方</td><td>version 列で、更新時に気付く</td>
 *       <td>{@code SELECT ... FOR UPDATE} で、読んだ時点で押さえる</td></tr>
 *   <tr><td>ロックする時間</td><td>ほぼ無い</td><td>画面を閉じるまで押さえたいが、そうもいかない</td></tr>
 *   <tr><td>競合したとき</td><td>更新しようとした人が気付く</td><td>あとから読む人が待たされる</td></tr>
 *   <tr><td>向く場面</td><td><b>Web の画面 (ほとんどこちら)</b></td><td>在庫の引き当てなど、短くて確実に押さえたい処理</td></tr>
 * </table>
 *
 * <p>Web で悲観ロックが向かないのは、<b>利用者が画面を開いたまま帰ってしまう</b>からです。
 * 「編集ボタンを押した瞬間にロックして、保存するまで保持する」は、
 * 昼休みに戻ってこない人が出た時点で破綻します。</p>
 */
public class CustomerDao {

    private static final String CREATE_TABLE = """
            CREATE TABLE IF NOT EXISTS customers (
                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code       VARCHAR(16)  NOT NULL,
                name       VARCHAR(120) NOT NULL,
                contact    VARCHAR(60)  NOT NULL,
                email      VARCHAR(120) NOT NULL,
                version    INT          NOT NULL,
                updated_at TIMESTAMP    NOT NULL,
                CONSTRAINT uk_customers_code UNIQUE (code)
            )
            """;

    private static final String COLUMNS = "id, code, name, contact, email, version, updated_at";

    private static final String[][] SEED = {
            {"AL-001", "株式会社アルファ", "田中 一郎", "tanaka@alpha.example.com"},
            {"BT-002", "ベータ商事", "佐藤 花子", "sato@beta.example.com"},
            {"GM-003", "ガンマ工業", "鈴木 次郎", "suzuki@gamma.example.com"},
            {"DL-004", "デルタ物産", "高橋 三郎", "takahashi@delta.example.com"}
    };

    private static boolean tableReady;

    public CustomerDao() {
        prepareTable();
    }

    /** テーブルを作り、空ならサンプルデータを入れる。 */
    public static synchronized void prepareTable() {
        if (tableReady) {
            return;
        }
        try (Connection connection = Database.getConnection();
             Statement statement = connection.createStatement()) {

            statement.execute(CREATE_TABLE);
            if (isEmpty(connection)) {
                insertSeedData(connection);
            }
            tableReady = true;
        } catch (SQLException e) {
            throw new IllegalStateException("customers テーブルを準備できませんでした", e);
        }
    }

    /** 取引先の一覧 (コード順)。 */
    public List<Customer> findAll() {
        List<Customer> customers = new ArrayList<>();
        String sql = "SELECT " + COLUMNS + " FROM customers ORDER BY code";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet rs = statement.executeQuery()) {

            while (rs.next()) {
                customers.add(toCustomer(rs));
            }
        } catch (SQLException e) {
            throw new IllegalStateException("取引先を取得できませんでした", e);
        }
        return customers;
    }

    /** ID で 1 件取り出す。見つからなければ空。 */
    public Optional<Customer> findById(long id) {
        String sql = "SELECT " + COLUMNS + " FROM customers WHERE id = ?";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setLong(1, id);
            try (ResultSet rs = statement.executeQuery()) {
                return rs.next() ? Optional.of(toCustomer(rs)) : Optional.empty();
            }
        } catch (SQLException e) {
            throw new IllegalStateException("取引先を取得できませんでした", e);
        }
    }

    /**
     * 取引先コードが既に使われているか。
     *
     * @param excludeId 自分自身は除く (編集のとき)。新規なら 0
     */
    public boolean existsCode(String code, long excludeId) {
        String sql = "SELECT COUNT(*) FROM customers WHERE code = ? AND id <> ?";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, code);
            statement.setLong(2, excludeId);
            try (ResultSet rs = statement.executeQuery()) {
                return rs.next() && rs.getInt(1) > 0;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("取引先コードを確認できませんでした", e);
        }
    }

    /**
     * 登録する。
     *
     * @return 採番された ID
     */
    public long insert(CustomerForm form) {
        String sql = """
                INSERT INTO customers (code, name, contact, email, version, updated_at)
                VALUES (?, ?, ?, ?, 1, ?)
                """;
        try (Connection connection = Database.getConnection();
             PreparedStatement statement =
                     connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            statement.setString(1, form.getCode());
            statement.setString(2, form.getName());
            statement.setString(3, form.getContact());
            statement.setString(4, form.getEmail());
            statement.setTimestamp(5, Timestamp.valueOf(LocalDateTime.now()));
            statement.executeUpdate();

            // 採番された ID を受け取る。完了画面に出したり、続けて明細を入れたりするのに使います
            try (ResultSet keys = statement.getGeneratedKeys()) {
                return keys.next() ? keys.getLong(1) : 0L;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("取引先を登録できませんでした", e);
        }
    }

    /**
     * 更新する (楽観ロック)。
     *
     * <p>条件に {@code version} を入れているので、
     * <b>画面を開いたあとに誰かが更新していれば 0 件になります</b>。</p>
     *
     * @return 更新できた行数。{@code 0} なら競合 (または行が消えていた)
     */
    public int update(CustomerForm form) {
        String sql = """
                UPDATE customers
                   SET code = ?, name = ?, contact = ?, email = ?,
                       version = version + 1, updated_at = ?
                 WHERE id = ? AND version = ?
                """;
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, form.getCode());
            statement.setString(2, form.getName());
            statement.setString(3, form.getContact());
            statement.setString(4, form.getEmail());
            statement.setTimestamp(5, Timestamp.valueOf(LocalDateTime.now()));
            statement.setLong(6, form.getIdValue());
            statement.setInt(7, form.getVersionValue());
            return statement.executeUpdate();

        } catch (SQLException e) {
            throw new IllegalStateException("取引先を更新できませんでした", e);
        }
    }

    /**
     * 削除する。
     *
     * <p>削除でも {@code version} を条件に入れます。
     * <b>「一覧を表示したあとに誰かが内容を変えた行を、気付かずに消す」</b>のを防ぐためです。</p>
     *
     * @return 削除できた行数。{@code 0} なら競合 (または既に消えていた)
     */
    public int delete(long id, int version) {
        String sql = "DELETE FROM customers WHERE id = ? AND version = ?";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setLong(1, id);
            statement.setInt(2, version);
            return statement.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException("取引先を削除できませんでした", e);
        }
    }

    /**
     * 「別の人が先に更新した」状況を作る (デモ専用)。
     *
     * <p>本来は別のブラウザやタブから更新してもらうところですが、
     * 1 人でも競合を試せるようにするためのものです。
     * <b>実際のアプリにこういう口を作ってはいけません。</b></p>
     *
     * @return 更新できた行数
     */
    public int simulateConcurrentUpdate(long id) {
        String sql = """
                UPDATE customers
                   SET contact = ?, version = version + 1, updated_at = ?
                 WHERE id = ?
                """;
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, "別の担当者（他の人が更新）");
            statement.setTimestamp(2, Timestamp.valueOf(LocalDateTime.now()));
            statement.setLong(3, id);
            return statement.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException("競合を作れませんでした", e);
        }
    }

    /** 初期状態に戻す (サンプルを何度も試せるように)。 */
    public void reset() {
        try (Connection connection = Database.getConnection()) {
            connection.setAutoCommit(false);
            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate("DELETE FROM customers");
                insertSeedData(connection);
                connection.commit();
            } catch (SQLException e) {
                connection.rollback();
                throw e;
            } finally {
                connection.setAutoCommit(true);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("初期化に失敗しました", e);
        }
    }

    private static Customer toCustomer(ResultSet rs) throws SQLException {
        Timestamp updatedAt = rs.getTimestamp("updated_at");
        return new Customer(
                rs.getLong("id"),
                rs.getString("code"),
                rs.getString("name"),
                rs.getString("contact"),
                rs.getString("email"),
                rs.getInt("version"),
                updatedAt == null ? null : updatedAt.toLocalDateTime());
    }

    private static boolean isEmpty(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT COUNT(*) FROM customers")) {
            return rs.next() && rs.getInt(1) == 0;
        }
    }

    private static void insertSeedData(Connection connection) throws SQLException {
        String sql = """
                INSERT INTO customers (code, name, contact, email, version, updated_at)
                VALUES (?, ?, ?, ?, 1, ?)
                """;
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            Timestamp now = Timestamp.valueOf(LocalDateTime.now());
            for (String[] row : SEED) {
                statement.setString(1, row[0]);
                statement.setString(2, row[1]);
                statement.setString(3, row[2]);
                statement.setString(4, row[3]);
                statement.setTimestamp(5, now);
                statement.addBatch();
            }
            statement.executeBatch();
        }
    }
}
