package com.example.servletsample.samples.list;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import com.example.servletsample.common.Database;

/**
 * 商品の検索 (DAO)。一覧・検索・ページングの SQL をここにまとめています。
 *
 * <p>ページングの基本は次の 2 回の問い合わせです。</p>
 * <ol>
 *   <li>{@code SELECT COUNT(*) ... WHERE 条件} … 全部で何件あるか (ページ数の計算に使う)</li>
 *   <li>{@code SELECT ... WHERE 条件 ORDER BY ... LIMIT ? OFFSET ?} … そのページの分だけ取り出す</li>
 * </ol>
 *
 * <p>「全件取ってきて Java 側で切り出す」方法でも画面は作れますが、
 * 件数が増えるとメモリも転送量も無駄になります。必要な行だけ DB に取り出させます。</p>
 */
public class ProductDao {

    private static final String CREATE_TABLE = """
            CREATE TABLE IF NOT EXISTS products (
                id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code       VARCHAR(16)  NOT NULL,
                name       VARCHAR(120) NOT NULL,
                category   VARCHAR(40)  NOT NULL,
                price      INT          NOT NULL,
                stock      INT          NOT NULL,
                updated_at DATE         NOT NULL
            )
            """;

    private static final String SELECT_COLUMNS = "id, code, name, category, price, stock, updated_at";

    /** LIKE 検索で {@code %} や {@code _} を「文字そのもの」として扱うためのエスケープ文字。 */
    private static final char LIKE_ESCAPE = '!';

    private static boolean tableReady;

    public ProductDao() {
        prepareTable();
    }

    /** テーブルを作り、空ならサンプルデータを入れる。 */
    public static synchronized void prepareTable() {
        if (tableReady) {
            return;
        }
        try (Connection connection = Database.getConnection();
             Statement statement = connection.createStatement()) {

            statement.execute(CREATE_TABLE);
            if (isEmpty(connection)) {
                insertSeedData(connection);
            }
            tableReady = true;
        } catch (SQLException e) {
            throw new IllegalStateException("products テーブルを準備できませんでした", e);
        }
    }

    /**
     * 条件に一致する商品を 1 ページ分取得する。
     *
     * @param search 画面から受け取った検索条件 (検査済み)
     * @return 表示する行 + 全件数
     */
    public Page<Product> search(ProductSearch search) {
        List<Object> parameters = new ArrayList<>();
        String where = buildWhere(search, parameters);

        int totalCount = count(where, parameters);

        // ORDER BY の列名は ? で置き換えられないので、ホワイトリストを通した値だけを埋める
        String sql = "SELECT " + SELECT_COLUMNS + " FROM products" + where
                + " ORDER BY " + search.getSortColumn() + " " + search.getDirection()
                + ", id ASC LIMIT ? OFFSET ?";

        List<Product> products = new ArrayList<>();
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            int index = bind(statement, parameters);
            statement.setInt(index++, search.getPageSize());
            statement.setInt(index, search.getOffset());

            try (ResultSet rs = statement.executeQuery()) {
                while (rs.next()) {
                    products.add(toProduct(rs));
                }
            }
        } catch (SQLException e) {
            throw new IllegalStateException("商品を検索できませんでした", e);
        }
        return Page.of(products, totalCount, search.getPage(), search.getPageSize());
    }

    /** 絞り込みに使うカテゴリの一覧 (重複なし)。 */
    public List<String> findCategories() {
        List<String> categories = new ArrayList<>();
        String sql = "SELECT DISTINCT category FROM products ORDER BY category";
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet rs = statement.executeQuery()) {

            while (rs.next()) {
                categories.add(rs.getString(1));
            }
            return categories;
        } catch (SQLException e) {
            throw new IllegalStateException("カテゴリを取得できませんでした", e);
        }
    }

    /** 登録されている商品の総数 (条件なし)。 */
    public int countAll() {
        return count("", new ArrayList<>());
    }

    /**
     * その検索条件で実行される SQL を組み立てて返す (画面で見せるための説明用)。
     *
     * <p>実際に実行する SQL と同じ組み立て方をしているので、
     * 「入力した条件が SQL のどこに効くのか」を確かめられます。</p>
     */
    public String describeSql(ProductSearch search) {
        String where = buildWhere(search, new ArrayList<>());
        return "SELECT " + SELECT_COLUMNS + "\n  FROM products" + where.replace(" WHERE ", "\n WHERE ")
                .replace(" AND ", "\n   AND ")
                + "\n ORDER BY " + search.getSortColumn() + " " + search.getDirection() + ", id ASC"
                + "\n LIMIT " + search.getPageSize() + " OFFSET " + search.getOffset();
    }

    // ------------------------------------------------------------------
    // 内部処理
    // ------------------------------------------------------------------

    /**
     * WHERE 句を組み立てる。
     *
     * <p>入力された値は SQL 文に直接つなげず、{@code ?} (プレースホルダ) にして
     * {@code parameters} に積みます。これが SQL インジェクション対策の基本です。</p>
     */
    private String buildWhere(ProductSearch search, List<Object> parameters) {
        StringBuilder where = new StringBuilder();

        if (!search.getKeyword().isEmpty()) {
            // 商品名・コード・カテゴリのどれかに含まれていれば一致とする
            where.append(" WHERE (LOWER(name) LIKE ? ESCAPE '").append(LIKE_ESCAPE).append("'")
                    .append(" OR LOWER(code) LIKE ? ESCAPE '").append(LIKE_ESCAPE).append("'")
                    .append(" OR LOWER(category) LIKE ? ESCAPE '").append(LIKE_ESCAPE).append("')");
            String pattern = "%" + escapeLike(search.getKeyword().toLowerCase()) + "%";
            parameters.add(pattern);
            parameters.add(pattern);
            parameters.add(pattern);
        }
        if (!search.getCategory().isEmpty()) {
            where.append(where.length() == 0 ? " WHERE " : " AND ").append("category = ?");
            parameters.add(search.getCategory());
        }
        if (search.isInStockOnly()) {
            where.append(where.length() == 0 ? " WHERE " : " AND ").append("stock > 0");
        }
        return where.toString();
    }

    private int count(String where, List<Object> parameters) {
        String sql = "SELECT COUNT(*) FROM products" + where;
        try (Connection connection = Database.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            bind(statement, parameters);
            try (ResultSet rs = statement.executeQuery()) {
                return rs.next() ? rs.getInt(1) : 0;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("件数を取得できませんでした", e);
        }
    }

    /** 積んでおいたパラメータを ? に順番に入れる。戻り値は次に使える番号。 */
    private static int bind(PreparedStatement statement, List<Object> parameters) throws SQLException {
        int index = 1;
        for (Object parameter : parameters) {
            statement.setObject(index++, parameter);
        }
        return index;
    }

    /**
     * LIKE の特殊文字をエスケープする。
     *
     * <p>{@code %} は「任意の文字列」、{@code _} は「任意の 1 文字」を表すため、
     * 利用者が入力した {@code 50%} をそのまま渡すと意図しない検索になります。</p>
     */
    static String escapeLike(String value) {
        StringBuilder escaped = new StringBuilder(value.length() + 8);
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (c == '%' || c == '_' || c == LIKE_ESCAPE) {
                escaped.append(LIKE_ESCAPE);
            }
            escaped.append(c);
        }
        return escaped.toString();
    }

    private static Product toProduct(ResultSet rs) throws SQLException {
        return new Product(
                rs.getLong("id"),
                rs.getString("code"),
                rs.getString("name"),
                rs.getString("category"),
                rs.getInt("price"),
                rs.getInt("stock"),
                rs.getObject("updated_at", LocalDate.class));
    }

    private static boolean isEmpty(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT COUNT(*) FROM products")) {
            return rs.next() && rs.getInt(1) == 0;
        }
    }

    // ------------------------------------------------------------------
    // サンプルデータ
    // ------------------------------------------------------------------

    /** {カテゴリ, 商品名, 価格} の並び。ページングが分かるように 60 件入れています。 */
    private static final String[][] SEED = {
            {"文房具", "ボールペン (黒・0.5mm)", "130"},
            {"文房具", "ゲルインクペン (青)", "150"},
            {"文房具", "シャープペンシル 0.5mm", "420"},
            {"文房具", "蛍光マーカー 5色セット", "580"},
            {"文房具", "消しゴム (まとめ買い 10個)", "760"},
            {"文房具", "修正テープ 5mm", "320"},
            {"文房具", "付箋 75×75mm 5冊パック", "690"},
            {"文房具", "クリアファイル A4 10枚組", "480"},
            {"文房具", "製本テープ 25mm", "260"},
            {"文房具", "名刺ケース (アルミ)", "1280"},

            {"事務機器", "シュレッダー (A4 クロスカット)", "18800"},
            {"事務機器", "ラミネーター A3 対応", "12400"},
            {"事務機器", "中綴じホチキス", "3600"},
            {"事務機器", "2穴パンチ (強力タイプ)", "2980"},
            {"事務機器", "電卓 12桁 卓上型", "2480"},
            {"事務機器", "タイムレコーダー", "24800"},
            {"事務機器", "ラベルライター (テープ幅 24mm)", "9800"},
            {"事務機器", "卓上裁断機 A4", "7600"},
            {"事務機器", "紙めくりクリーム", "380"},
            {"事務機器", "回転印 (日付)", "2200"},

            {"オフィス家具", "オフィスチェア (メッシュ)", "23800"},
            {"オフィス家具", "電動昇降デスク 120cm", "68000"},
            {"オフィス家具", "サイドワゴン 3段", "14800"},
            {"オフィス家具", "書棚 (木製・5段)", "19800"},
            {"オフィス家具", "ホワイトボード 90×60cm", "8900"},
            {"オフィス家具", "デスクパーテーション", "5400"},
            {"オフィス家具", "コートハンガー (スチール)", "6800"},
            {"オフィス家具", "折りたたみ会議テーブル", "16800"},
            {"オフィス家具", "スツール (昇降式)", "7400"},
            {"オフィス家具", "マガジンラック", "4300"},

            {"キッチン", "電気ケトル 1.0L", "4980"},
            {"キッチン", "コーヒーメーカー 5杯用", "8800"},
            {"キッチン", "ステンレスマグ 350ml", "2180"},
            {"キッチン", "業務用エアーポット 2.2L", "6400"},
            {"キッチン", "冷水筒 1.8L", "980"},
            {"キッチン", "紙コップ 205ml 100個入", "740"},
            {"キッチン", "ウォーターサーバー用ラック", "5200"},
            {"キッチン", "卓上クリーナー", "1680"},
            {"キッチン", "保冷バッグ 15L", "2480"},
            {"キッチン", "水切りかご (ステンレス)", "3480"},

            {"デジタル家電", "ノートPCスタンド (アルミ)", "3980"},
            {"デジタル家電", "USB-C ハブ 7ポート", "4680"},
            {"デジタル家電", "ワイヤレスマウス (静音)", "2780"},
            {"デジタル家電", "静音キーボード (日本語配列)", "5800"},
            {"デジタル家電", "27インチ モニター (WQHD)", "38800"},
            {"デジタル家電", "Web カメラ フル HD", "6480"},
            {"デジタル家電", "ヘッドセット (ノイズキャンセル)", "9800"},
            {"デジタル家電", "モバイルバッテリー 10000mAh", "3980"},
            {"デジタル家電", "外付け SSD 1TB", "12800"},
            {"デジタル家電", "HDMI ケーブル 2m", "1280"},

            {"アウトドア", "折りたたみチェア (軽量)", "3480"},
            {"アウトドア", "レジャーシート 200×200cm", "1980"},
            {"アウトドア", "クーラーボックス 20L", "7800"},
            {"アウトドア", "LED ランタン (充電式)", "4280"},
            {"アウトドア", "タープテント 3×3m", "19800"},
            {"アウトドア", "トレッキングポール 2本組", "6800"},
            {"アウトドア", "保温ボトル 500ml", "3280"},
            {"アウトドア", "レインポンチョ", "2480"},
            {"アウトドア", "防水バックパック 30L", "8900"},
            {"アウトドア", "折りたたみ傘 (晴雨兼用)", "2980"},
    };

    private static void insertSeedData(Connection connection) throws SQLException {
        String sql = """
                INSERT INTO products (code, name, category, price, stock, updated_at)
                VALUES (?, ?, ?, ?, ?, ?)
                """;
        LocalDate today = LocalDate.now();
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            for (int i = 0; i < SEED.length; i++) {
                String[] row = SEED[i];
                statement.setString(1, String.format("P-%04d", i + 1));
                statement.setString(2, row[1]);
                statement.setString(3, row[0]);
                statement.setInt(4, Integer.parseInt(row[2]));
                // 7 件に 1 件くらい在庫切れにして、絞り込みの動作が分かるようにする
                statement.setInt(5, i % 7 == 3 ? 0 : (i * 13) % 80 + 1);
                statement.setObject(6, today.minusDays((i * 11L) % 180));
                statement.addBatch();
            }
            statement.executeBatch();
        }
    }
}
